[workspace]
members = [
    "apps/ll-builder",
    "apps/ll-cli",
    "apps/ll-driver-detect",
    "apps/ll-init",
    "apps/ll-package-manager",
    "apps/ll-system-helper",
    "apps/uab",
    "crates/linyaps-api",
    "crates/linyaps-core",
    "crates/linyaps-dbus",
    "crates/linyaps-i18n",
    "crates/linyaps-repository",
]
resolver = "3"

[workspace.package]
version = "1.14.0"
edition = "2024"
rust-version = "1.92"
license = "LGPL-3.0-or-later"

[workspace.dependencies]
anyhow = "1.0.102"
bzip2 = "0.6.1"
fs-core = { package = "am-fs-core", version = "0.2.2" }
fs-erofs = { package = "am-fs-erofs", path = "vendor/am-fs-erofs" }
async-channel = "2.5.0"
async-io = "2.6.0"
async-lock = "3.4.2"
clap = { version = "4.5.60", features = ["derive"] }
flate2 = "1.1.9"
futures-lite = "2.6.1"
fuser = { version = "0.17.0", default-features = false, features = ["abi-7-31"] }
gix = { version = "0.83.0", default-features = false, features = ["blocking-http-transport-reqwest-rust-tls", "basic", "comfort", "sha1", "worktree-mutation"] }
goblin = "0.10.3"
libc = "0.2.177"
linyaps-api = { path = "crates/linyaps-api" }
linyaps-core = { path = "crates/linyaps-core" }
linyaps-dbus = { path = "crates/linyaps-dbus" }
linyaps-i18n = { path = "crates/linyaps-i18n" }
linyaps-repository = { path = "crates/linyaps-repository" }
lzma-rs = "0.3.0"
md-5 = "0.11.0"
oci-spec = { version = "0.10.0", features = ["runtime"] }
ostrya = { version = "0.0.1", default-features = false, features = ["tokio"] }
ostrya-core = "0.0.1"
patchkit = "0.3.3"
reqwest = { version = "0.13.4", default-features = false, features = ["json", "multipart", "rustls-no-provider", "stream"] }
ruzstd = "0.8.3"
rustls-rustcrypto = "0.0.2-alpha"
rustix = { version = "1.1.4", default-features = false, features = ["fs", "process", "std"] }
semver = "1.0.28"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
serde_yml = "0.0.12"
sha2 = "0.11.0"
sha1 = "0.11.0"
thiserror = "2.0.18"
tokio = { version = "1.48.0", features = ["macros", "rt-multi-thread", "time"] }
zbus = { version = "5.18.0", default-features = false, features = ["blocking-api", "p2p", "tokio"] }
zvariant = "5.13.1"
wayland-client = "0.31.11"
wayland-protocols = { version = "0.32.9", features = ["client", "staging"] }

[profile.release]
lto = "thin"
codegen-units = 1
strip = true
