[package]
name = "ll-system-helper"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Linyaps system integration generators and installer"

[[bin]]
name = "ll-system-helper"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
goblin.workspace = true
linyaps-i18n.workspace = true

[dev-dependencies]
tempfile = "3.27.0"
