#!/bin/sh
set -e

if [ -z "${DPKG_ROOT:-}" ]; then
    if [ "$1" = purge ] && command -v deb-systemd-helper >/dev/null 2>&1; then
        deb-systemd-helper purge org.deepin.linglong.PackageManager.service >/dev/null || true
    fi
    if [ -d /run/systemd/system ]; then
        systemctl --system daemon-reload >/dev/null || true
    fi
    if command -v update-desktop-database >/dev/null 2>&1; then
        update-desktop-database -q /usr/share/applications || true
    fi
    if command -v update-mime-database >/dev/null 2>&1; then
        update-mime-database /usr/share/mime >/dev/null || true
    fi
fi
#DEBHELPER#
exit 0
