[package]
name = "linyaps-dbus"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Pure Rust D-Bus bindings for Linyaps"

[dependencies]
async-channel.workspace = true
async-io.workspace = true
futures-lite.workspace = true
linyaps-api.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
zbus.workspace = true
zvariant.workspace = true
