pub fn get(language: &str, key: &str) -> Option<&'static str> {
    Some(match (language, key) {
        ("ca", "minimal") => include_str!("../help/localized/ca/minimal.txt"),
        ("es", "minimal") => include_str!("../help/localized/es/minimal.txt"),
        ("fi", "minimal") => include_str!("../help/localized/fi/minimal.txt"),
        ("fr", "minimal") => include_str!("../help/localized/fr/minimal.txt"),
        ("it", "minimal") => include_str!("../help/localized/it/minimal.txt"),
        ("pl", "minimal") => include_str!("../help/localized/pl/minimal.txt"),
        ("pt_BR", "minimal") => include_str!("../help/localized/pt_BR/minimal.txt"),
        ("ru", "minimal") => include_str!("../help/localized/ru/minimal.txt"),
        ("sq", "minimal") => include_str!("../help/localized/sq/minimal.txt"),
        ("uk", "minimal") => include_str!("../help/localized/uk/minimal.txt"),
        ("zh_CN", "minimal") => include_str!("../help/localized/zh_CN/minimal.txt"),
        ("zh_HK", "minimal") => include_str!("../help/localized/zh_HK/minimal.txt"),
        ("zh_TW", "minimal") => include_str!("../help/localized/zh_TW/minimal.txt"),
        ("ca", "analyze") => include_str!("../help/localized/ca/analyze.txt"),
        ("ca", "analyze_depends") => include_str!("../help/localized/ca/analyze_depends.txt"),
        ("ca", "analyze_help-all") => include_str!("../help/localized/ca/analyze_help-all.txt"),
        ("ca", "analyze_size") => include_str!("../help/localized/ca/analyze_size.txt"),
        ("ca", "install") => include_str!("../help/localized/ca/install.txt"),
        ("es", "analyze") => include_str!("../help/localized/es/analyze.txt"),
        ("es", "analyze_depends") => include_str!("../help/localized/es/analyze_depends.txt"),
        ("es", "analyze_help-all") => include_str!("../help/localized/es/analyze_help-all.txt"),
        ("es", "analyze_size") => include_str!("../help/localized/es/analyze_size.txt"),
        ("es", "install") => include_str!("../help/localized/es/install.txt"),
        ("fi", "analyze") => include_str!("../help/localized/fi/analyze.txt"),
        ("fi", "analyze_depends") => include_str!("../help/localized/fi/analyze_depends.txt"),
        ("fi", "analyze_help-all") => include_str!("../help/localized/fi/analyze_help-all.txt"),
        ("fi", "analyze_size") => include_str!("../help/localized/fi/analyze_size.txt"),
        ("fi", "install") => include_str!("../help/localized/fi/install.txt"),
        ("fr", "inspect_dir") => include_str!("../help/localized/fr/inspect_dir.txt"),
        ("fr", "repo_add") => include_str!("../help/localized/fr/repo_add.txt"),
        ("fr", "repo_disable-mirror") => {
            include_str!("../help/localized/fr/repo_disable-mirror.txt")
        }
        ("fr", "repo_enable-mirror") => include_str!("../help/localized/fr/repo_enable-mirror.txt"),
        ("fr", "repo_help-all") => include_str!("../help/localized/fr/repo_help-all.txt"),
        ("fr", "repo_remove") => include_str!("../help/localized/fr/repo_remove.txt"),
        ("fr", "repo_set-default") => include_str!("../help/localized/fr/repo_set-default.txt"),
        ("fr", "repo_set-priority") => include_str!("../help/localized/fr/repo_set-priority.txt"),
        ("fr", "repo_update") => include_str!("../help/localized/fr/repo_update.txt"),
        ("it", "analyze") => include_str!("../help/localized/it/analyze.txt"),
        ("it", "analyze_depends") => include_str!("../help/localized/it/analyze_depends.txt"),
        ("it", "analyze_help-all") => include_str!("../help/localized/it/analyze_help-all.txt"),
        ("it", "analyze_size") => include_str!("../help/localized/it/analyze_size.txt"),
        ("it", "install") => include_str!("../help/localized/it/install.txt"),
        ("pl", "analyze") => include_str!("../help/localized/pl/analyze.txt"),
        ("pl", "analyze_depends") => include_str!("../help/localized/pl/analyze_depends.txt"),
        ("pl", "analyze_help-all") => include_str!("../help/localized/pl/analyze_help-all.txt"),
        ("pl", "analyze_size") => include_str!("../help/localized/pl/analyze_size.txt"),
        ("pl", "install") => include_str!("../help/localized/pl/install.txt"),
        ("pt_BR", "analyze") => include_str!("../help/localized/pt_BR/analyze.txt"),
        ("pt_BR", "analyze_depends") => include_str!("../help/localized/pt_BR/analyze_depends.txt"),
        ("pt_BR", "analyze_help-all") => {
            include_str!("../help/localized/pt_BR/analyze_help-all.txt")
        }
        ("pt_BR", "analyze_size") => include_str!("../help/localized/pt_BR/analyze_size.txt"),
        ("pt_BR", "install") => include_str!("../help/localized/pt_BR/install.txt"),
        ("ru", "analyze") => include_str!("../help/localized/ru/analyze.txt"),
        ("ru", "analyze_depends") => include_str!("../help/localized/ru/analyze_depends.txt"),
        ("ru", "analyze_help-all") => include_str!("../help/localized/ru/analyze_help-all.txt"),
        ("ru", "analyze_size") => include_str!("../help/localized/ru/analyze_size.txt"),
        ("ru", "help-all") => include_str!("../help/localized/ru/help-all.txt"),
        ("ru", "install") => include_str!("../help/localized/ru/install.txt"),
        ("ru", "ps") => include_str!("../help/localized/ru/ps.txt"),
        ("sq", "help-all") => include_str!("../help/localized/sq/help-all.txt"),
        ("sq", "inspect_dir") => include_str!("../help/localized/sq/inspect_dir.txt"),
        ("sq", "upgrade") => include_str!("../help/localized/sq/upgrade.txt"),
        ("uk", "help-all") => include_str!("../help/localized/uk/help-all.txt"),
        ("uk", "inspect_dir") => include_str!("../help/localized/uk/inspect_dir.txt"),
        ("uk", "ps") => include_str!("../help/localized/uk/ps.txt"),
        ("zh_CN", "analyze") => include_str!("../help/localized/zh_CN/analyze.txt"),
        ("zh_CN", "analyze_depends") => include_str!("../help/localized/zh_CN/analyze_depends.txt"),
        ("zh_CN", "analyze_help-all") => {
            include_str!("../help/localized/zh_CN/analyze_help-all.txt")
        }
        ("zh_CN", "analyze_size") => include_str!("../help/localized/zh_CN/analyze_size.txt"),
        ("zh_CN", "install") => include_str!("../help/localized/zh_CN/install.txt"),
        ("zh_HK", "analyze") => include_str!("../help/localized/zh_HK/analyze.txt"),
        ("zh_HK", "analyze_depends") => include_str!("../help/localized/zh_HK/analyze_depends.txt"),
        ("zh_HK", "analyze_help-all") => {
            include_str!("../help/localized/zh_HK/analyze_help-all.txt")
        }
        ("zh_HK", "analyze_size") => include_str!("../help/localized/zh_HK/analyze_size.txt"),
        ("zh_HK", "content") => include_str!("../help/localized/zh_HK/content.txt"),
        ("zh_HK", "enter") => include_str!("../help/localized/zh_HK/enter.txt"),
        ("zh_HK", "help-all") => include_str!("../help/localized/zh_HK/help-all.txt"),
        ("zh_HK", "info") => include_str!("../help/localized/zh_HK/info.txt"),
        ("zh_HK", "inspect") => include_str!("../help/localized/zh_HK/inspect.txt"),
        ("zh_HK", "inspect_dir") => include_str!("../help/localized/zh_HK/inspect_dir.txt"),
        ("zh_HK", "install") => include_str!("../help/localized/zh_HK/install.txt"),
        ("zh_HK", "list") => include_str!("../help/localized/zh_HK/list.txt"),
        ("zh_HK", "prune") => include_str!("../help/localized/zh_HK/prune.txt"),
        ("zh_HK", "root") => include_str!("../help/localized/zh_HK/root.txt"),
        ("zh_HK", "search") => include_str!("../help/localized/zh_HK/search.txt"),
        ("zh_TW", "analyze") => include_str!("../help/localized/zh_TW/analyze.txt"),
        ("zh_TW", "analyze_depends") => include_str!("../help/localized/zh_TW/analyze_depends.txt"),
        ("zh_TW", "analyze_help-all") => {
            include_str!("../help/localized/zh_TW/analyze_help-all.txt")
        }
        ("zh_TW", "analyze_size") => include_str!("../help/localized/zh_TW/analyze_size.txt"),
        ("zh_TW", "enter") => include_str!("../help/localized/zh_TW/enter.txt"),
        ("zh_TW", "help-all") => include_str!("../help/localized/zh_TW/help-all.txt"),
        ("zh_TW", "install") => include_str!("../help/localized/zh_TW/install.txt"),
        ("zh_TW", "root") => include_str!("../help/localized/zh_TW/root.txt"),
        _ => return None,
    })
}
