use std::collections::BTreeSet;
use std::fs;
use std::os::unix::fs::symlink;
use std::path::{Component, Path, PathBuf};

use anyhow::{Context, Result, bail};

use crate::source::{clear_path, copy_tree};

const UAB_BLACKLIST: &str = include_str!("../data/uab-blacklist");

pub fn bundled_library_blacklist(enabled: bool) -> BTreeSet<String> {
    if !enabled {
        return BTreeSet::new();
    }
    UAB_BLACKLIST
        .lines()
        .filter(|line| !line.is_empty() && !line.starts_with('#'))
        .map(str::to_string)
        .collect()
}

pub fn load_needed_files(path: &Path) -> Result<BTreeSet<PathBuf>> {
    let content = fs::read_to_string(path).with_context(|| {
        format!(
            "{} is generated by the runtime check but is not available",
            path.display()
        )
    })?;
    let document: serde_json::Value = serde_yml::from_str(&content)
        .with_context(|| format!("invalid dependency file {}", path.display()))?;
    let depends = document
        .get("depends")
        .and_then(serde_json::Value::as_array)
        .with_context(|| format!("the content of {} is invalid", path.display()))?;
    let mut output = BTreeSet::new();
    for value in depends {
        let value = value
            .as_str()
            .with_context(|| format!("the content of {} is invalid", path.display()))?;
        if value.is_empty() {
            continue;
        }
        let path = PathBuf::from(value);
        if !path.is_absolute()
            || path
                .components()
                .any(|component| matches!(component, Component::ParentDir))
        {
            bail!("invalid dependency path: {}", path.display());
        }
        if !output.insert(path.clone()) {
            bail!("duplicate dependency path: {}", path.display());
        }
    }
    Ok(output)
}

pub fn copy_filtered_layer(
    source: &Path,
    destination: &Path,
    excludes: &[String],
    includes: &[String],
    blacklist: &BTreeSet<String>,
) -> Result<bool> {
    fs::create_dir_all(destination)?;
    for entry in fs::read_dir(source)? {
        let entry = entry?;
        if entry.file_name() == "files" {
            continue;
        }
        copy_tree(&entry.path(), &destination.join(entry.file_name()))?;
    }
    let source_files = source.join("files");
    if !source_files.is_dir() {
        bail!("there isn't a files dir in layer {}", source.display());
    }
    let destination_files = destination.join("files");
    fs::create_dir_all(&destination_files)?;
    let mut expanded_excludes = expand_filters(&source_files, excludes)?;
    let expanded_includes = expand_filters(&source_files, includes)?;
    for included in &expanded_includes {
        expanded_excludes.remove(included);
    }

    let mut leaves = Vec::new();
    collect_leaves(&source_files, &source_files, &mut leaves)?;
    let mut minified = false;
    for relative in leaves {
        let explicitly_included = expanded_includes.contains(&relative);
        if expanded_excludes.contains(&relative) {
            minified = true;
            continue;
        }
        if !explicitly_included
            && relative
                .file_name()
                .and_then(|name| name.to_str())
                .is_some_and(|name| blacklisted(name, blacklist))
        {
            continue;
        }
        copy_selected_entry(&source_files, &destination_files, &relative)?;
    }
    for relative in expanded_includes {
        copy_selected_entry(&source_files, &destination_files, &relative)?;
    }
    Ok(minified)
}

pub fn append_base_dependencies(
    base_files: &Path,
    runtime_files: &Path,
    needed: &BTreeSet<PathBuf>,
    blacklist: &BTreeSet<String>,
    triplet: &str,
) -> Result<()> {
    let fake_prefix = runtime_files.join("lib").join(triplet);
    for path in needed {
        let filename = path
            .file_name()
            .and_then(|name| name.to_str())
            .with_context(|| format!("invalid dependency path: {}", path.display()))?;
        if blacklisted(filename, blacklist) {
            continue;
        }
        let relative = path
            .strip_prefix("/")
            .with_context(|| format!("invalid dependency path: {}", path.display()))?;
        let Some((source, mut destination)) =
            prepare_symlink_chain(base_files, runtime_files, relative)?
        else {
            bail!("dependency {} doesn't exist in base", path.display());
        };
        let metadata = fs::symlink_metadata(&source)?;
        if !metadata.is_file() {
            bail!("dependency {} isn't a regular file", source.display());
        }
        if destination.strip_prefix(&fake_prefix).is_err() || destination == fake_prefix {
            destination = fake_prefix.join(
                source
                    .file_name()
                    .context("dependency target has no file name")?,
            );
        }
        if fs::symlink_metadata(&destination).is_ok() {
            continue;
        }
        if let Some(parent) = destination.parent() {
            fs::create_dir_all(parent)?;
        }
        fs::copy(&source, &destination)?;
        fs::set_permissions(destination, metadata.permissions())?;
    }
    Ok(())
}

pub fn filter_path(path: &str) -> Result<&Path> {
    let Some(path) = path.strip_prefix('/') else {
        bail!("invalid filter path: {path}");
    };
    if path
        .split('/')
        .any(|component| component == ".." || component == ".")
    {
        bail!("invalid filter path: /{path}");
    }
    Ok(Path::new(path))
}

fn expand_filters(root: &Path, filters: &[String]) -> Result<BTreeSet<PathBuf>> {
    let mut output = BTreeSet::new();
    for filter in filters {
        let relative = filter_path(filter)?;
        let path = root.join(relative);
        let metadata = match fs::symlink_metadata(&path) {
            Ok(metadata) => metadata,
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => continue,
            Err(error) => return Err(error.into()),
        };
        if metadata.is_file() {
            output.insert(relative.to_path_buf());
        } else if metadata.is_dir() && !metadata.file_type().is_symlink() {
            collect_leaves(root, &path, &mut output)?;
        }
    }
    Ok(output)
}

trait LeafCollection {
    fn add(&mut self, path: PathBuf);
}

impl LeafCollection for Vec<PathBuf> {
    fn add(&mut self, path: PathBuf) {
        self.push(path);
    }
}

impl LeafCollection for BTreeSet<PathBuf> {
    fn add(&mut self, path: PathBuf) {
        self.insert(path);
    }
}

fn collect_leaves<T: LeafCollection>(root: &Path, path: &Path, output: &mut T) -> Result<()> {
    for entry in fs::read_dir(path)? {
        let path = entry?.path();
        let metadata = fs::symlink_metadata(&path)?;
        if metadata.is_dir() && !metadata.file_type().is_symlink() {
            collect_leaves(root, &path, output)?;
        } else if metadata.is_file() || metadata.file_type().is_symlink() {
            output.add(path.strip_prefix(root)?.to_path_buf());
        }
    }
    Ok(())
}

fn blacklisted(filename: &str, blacklist: &BTreeSet<String>) -> bool {
    blacklist
        .iter()
        .any(|entry| entry.starts_with(filename) || filename.starts_with(entry))
}

fn copy_selected_entry(source_root: &Path, destination_root: &Path, relative: &Path) -> Result<()> {
    let Some((source, destination)) =
        prepare_symlink_chain(source_root, destination_root, relative)?
    else {
        return Ok(());
    };
    let metadata = fs::symlink_metadata(&source)?;
    if metadata.is_dir() {
        fs::create_dir_all(destination)?;
        return Ok(());
    }
    if fs::symlink_metadata(&destination).is_ok() {
        return Ok(());
    }
    if let Some(parent) = destination.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::copy(&source, &destination)?;
    fs::set_permissions(destination, metadata.permissions())?;
    Ok(())
}

fn prepare_symlink_chain(
    source_root: &Path,
    destination_root: &Path,
    relative: &Path,
) -> Result<Option<(PathBuf, PathBuf)>> {
    let Some(mut relative) = normalize_relative(relative) else {
        bail!("invalid layer path: {}", relative.display());
    };
    for _ in 0..40 {
        let source = source_root.join(&relative);
        let destination = destination_root.join(&relative);
        let metadata = match fs::symlink_metadata(&source) {
            Ok(metadata) => metadata,
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => return Ok(None),
            Err(error) => return Err(error.into()),
        };
        if !metadata.file_type().is_symlink() {
            return Ok(Some((source, destination)));
        }
        let target = fs::read_link(&source)?;
        if let Some(parent) = destination.parent() {
            fs::create_dir_all(parent)?;
        }
        if fs::symlink_metadata(&destination).is_ok() {
            clear_path(&destination)?;
        }
        symlink(&target, &destination)?;
        let next = if target.is_absolute() {
            target.strip_prefix("/").unwrap_or(&target).to_path_buf()
        } else {
            relative.parent().unwrap_or(Path::new("")).join(target)
        };
        let Some(next) = normalize_relative(&next) else {
            bail!("symbolic link escapes layer: {}", source.display());
        };
        relative = next;
    }
    bail!(
        "too many symbolic links while resolving {}",
        relative.display()
    )
}

fn normalize_relative(path: &Path) -> Option<PathBuf> {
    if path.is_absolute() {
        return None;
    }
    let mut normalized = PathBuf::new();
    for component in path.components() {
        match component {
            Component::CurDir => {}
            Component::Normal(component) => normalized.push(component),
            Component::ParentDir => {
                if !normalized.pop() {
                    return None;
                }
            }
            Component::RootDir | Component::Prefix(_) => return None,
        }
    }
    Some(normalized)
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::tempdir;

    #[test]
    fn filters_blacklist_and_include_overrides() {
        let temporary = tempdir().unwrap();
        let source = temporary.path().join("source");
        let destination = temporary.path().join("destination");
        fs::create_dir_all(source.join("files/lib")).unwrap();
        fs::write(source.join("info.json"), "info").unwrap();
        fs::write(source.join("files/lib/libc.so.6"), "libc").unwrap();
        fs::write(source.join("files/lib/libkeep.so"), "keep").unwrap();
        fs::write(source.join("files/lib/libdrop.so"), "drop").unwrap();
        let blacklist = ["libc.so.6".to_string()].into_iter().collect();
        let minified = copy_filtered_layer(
            &source,
            &destination,
            &["/lib".to_string()],
            &["/lib/libkeep.so".to_string(), "/lib/libc.so.6".to_string()],
            &blacklist,
        )
        .unwrap();
        assert!(minified);
        assert!(destination.join("info.json").is_file());
        assert!(destination.join("files/lib/libkeep.so").is_file());
        assert!(destination.join("files/lib/libc.so.6").is_file());
        assert!(!destination.join("files/lib/libdrop.so").exists());
    }

    #[test]
    fn copies_relative_symbolic_link_chain() {
        let temporary = tempdir().unwrap();
        let source = temporary.path().join("source");
        let destination = temporary.path().join("destination");
        fs::create_dir_all(source.join("files/lib")).unwrap();
        fs::write(source.join("info.json"), "info").unwrap();
        fs::write(source.join("files/lib/libdemo.so.1.0"), "library").unwrap();
        symlink("libdemo.so.1.0", source.join("files/lib/libdemo.so.1")).unwrap();
        copy_filtered_layer(&source, &destination, &[], &[], &BTreeSet::new()).unwrap();
        assert_eq!(
            fs::read_link(destination.join("files/lib/libdemo.so.1")).unwrap(),
            PathBuf::from("libdemo.so.1.0")
        );
        assert_eq!(
            fs::read_to_string(destination.join("files/lib/libdemo.so.1.0")).unwrap(),
            "library"
        );
    }

    #[test]
    fn validates_dependency_manifest() {
        let temporary = tempdir().unwrap();
        let path = temporary.path().join("depends.yaml");
        fs::write(&path, "depends:\n - /usr/lib/libdemo.so\n").unwrap();
        assert_eq!(
            load_needed_files(&path).unwrap(),
            [PathBuf::from("/usr/lib/libdemo.so")].into_iter().collect()
        );
        fs::write(&path, "depends:\n - ../escape\n").unwrap();
        assert!(load_needed_files(&path).is_err());
    }
}
