[package]
name = "ll-package-manager"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Linyaps package-manager D-Bus service"

[[bin]]
name = "ll-package-manager"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
async-channel.workspace = true
async-lock.workspace = true
futures-lite.workspace = true
linyaps-api.workspace = true
linyaps-core.workspace = true
linyaps-dbus.workspace = true
linyaps-i18n.workspace = true
linyaps-repository.workspace = true
libc.workspace = true
serde_json.workspace = true
sha2.workspace = true
tokio.workspace = true
zbus.workspace = true
zvariant.workspace = true

[dev-dependencies]
ostrya.workspace = true
tempfile = "3.27.0"
